var tools = ["Anaconda Navigator", "Firefox Quantum", "F.lux", "Google Chrome", "LaTeX for Windows", "TexMaker", "Discord", "VirtualBox", "PuTTY", "SoftEther", "Python", "Notepad++", 
"ShareX", "git", "Keybase", "Java", "eclipse", "Android Studio", "Wireshark", "Process Hacker", "IntelliJ IDEA", "Audacity", "Steam", "VS Code", "GIMP2", "OpenCV"]

var links = ["https://www.anaconda.com/download/", "https://www.mozilla.org/en-US/firefox/", "https://justgetflux.com/", "https://www.google.com/chrome/browser/desktop/index.html", "https://miktex.org/download", "http://www.xm1math.net/texmaker", "https://discordapp.com/download", "https://www.virtualbox.org/wiki/Downloads", "http://www.putty.org/", "http://www.softether-download.com/en.aspx?product=softether", "https://www.python.org/downloads/", "https://notepad-plus-plus.org/download/v7.5.1.html", "https://getsharex.com/", "https://git-scm.com/downloads", "https://keybase.io/download", "https://java.com/en/download/win10.jsp", "https://www.eclipse.org/downloads/packages/", "https://developer.android.com/studio/index.html", "https://www.wireshark.org/download.html", "http://processhacker.sourceforge.net/", "https://www.jetbrains.com/idea/", "https://www.audacityteam.org/", "https://store.steampowered.com/about/", "https://code.visualstudio.com/", "https://www.gimp.org/", "https://opencv.org/"]

var image_icons = ['../img/icons/anaconda-logo-300x300.png', '../img/icons/firefoxsquare.jpg', '../img/icons/flux-icon-sm.png', '../img/icons/Google-Chrome-icon.png', '../img/icons/TeXworks256.png', '../img/icons/Texmaker_Logo.png', '../img/icons/2c21aeda16de354ba5334551a883b481.png', '../img/icons/Virtualbox_logo.png', '../img/icons/flat,800x800,075,f.jpg', '../img/icons/imgingest-1829430798785509634.png', '../img/icons/2000px-Python-logo-notext.svg.png', '../img/icons/notepad_plus_intro.png', '../img/icons/ShareX_Logo.png', '../img/icons/logomark-orange@2x.png', '../img/icons/keybase.io-logo.png', '../img/icons/java-logo-vector-768x768.png', '../img/icons/eclipse-logo-85FE4BEA34-seeklogo.com.png', '../img/icons/android-studio.png', '../img/icons/sflogo.png', '../img/icons/Process-Hacker.png', '../img/icons/download.jpg', '../img/icons/Audacity_Logo.svg.png', '../img/icons/steam-logo-transparent.png', '../img/icons/512px-Visual_Studio_Code_1.18_icon.svg.png', '../img/icons/wilber-big.png', '../img/icons/logo.png']

var table_location = document.getElementById('material-table-container');
 for(var x = 0; x < tools.length; x++){   
	table_location.innerHTML += `<tr>\n  <td class="mdl-data-table__cell--non-numeric ">\n    <span class="mdl-chip mdl-chip--contact">\n      <img class="mdl-chip__contact" src="${image_icons[x]}"></img>\n      <span class="mdl-chip__text">${tools[x]}</span>\n    </span>\n  </td>\n  <td class="mdl-data-table__cell--non-numeric resource-link">\n    <a href="${links[x]}">\n      ${links[x]}\n    </a>\n  </td>\n</tr>`
	}