var tools = ["Anaconda Navigator", "Firefox Quantum", "F.lux", "Google Chrome", "LaTeX for Windows", "TexMaker", "Discord", "VirtualBox", "PuTTY", "SoftEther", "Python", "Notepad++", 
"ShareX", "git", "Keybase", "Java", "eclipse", "Android Studio", "Wireshark", "Process Hacker", "IntelliJ IDEA", "Audacity", "Steam", "VS Code", "GIMP2", "OpenCV"]

var links = ["https://www.anaconda.com/download/", "https://www.mozilla.org/en-US/firefox/", "https://justgetflux.com/", "https://www.google.com/chrome/browser/desktop/index.html", "https://miktex.org/download", "http://www.xm1math.net/texmaker", "https://discordapp.com/download", "https://www.virtualbox.org/wiki/Downloads", "http://www.putty.org/", "http://www.softether-download.com/en.aspx?product=softether", "https://www.python.org/downloads/", "https://notepad-plus-plus.org/download/v7.5.1.html", "https://getsharex.com/", "https://git-scm.com/downloads", "https://keybase.io/download", "https://java.com/en/download/win10.jsp", "https://www.eclipse.org/downloads/packages/", "https://developer.android.com/studio/index.html", "https://www.wireshark.org/download.html", "http://processhacker.sourceforge.net/", "https://www.jetbrains.com/idea/", "https://www.audacityteam.org/", "https://store.steampowered.com/about/", "https://code.visualstudio.com/", "https://www.gimp.org/", "https://opencv.org/"]

var image_icons = ["https://datarebellion.com/wp-content/uploads/2018/04/anaconda-logo-300x300.png", "https://i0.wp.com/cynmackley.com/wp-content/uploads/2017/09/firefoxsquare.jpg", "https://justgetflux.com/flux-icon-sm.png", "https://icons.iconarchive.com/icons/marcus-roberto/google-play/256/Google-Chrome-icon.png", "https://www.tug.org/texworks/img/TeXworks256.png", "https://upload.wikimedia.org/wikipedia/commons/4/42/Texmaker_Logo.png", "https://discordapp.com/assets/2c21aeda16de354ba5334551a883b481.png", "https://upload.wikimedia.org/wikipedia/commons/d/d5/Virtualbox_logo.png", "https://ih0.redbubble.net/image.351920104.8205/flat,800x800,075,f.jpg", "https://dl1.cbsistatic.com/i/2016/07/06/e1e86e8c-5f81-480c-a55d-b91ed17c2fdc/03c39ec529a0b19e1c6700e2a2cd02a7/imgingest-1829430798785509634.png", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/2000px-Python-logo-notext.svg.png", "https://static.makeuseof.com/wp-content/uploads/2012/01/notepad_plus_intro.png", "https://getsharex.com/img/ShareX_Logo.png", "https://git-scm.com/images/logos/logomark-orange@2x.png", "https://www.qownnotes.org/var/bekerle/storage/images/_aliases/reference/media/images/keybase.io-logo/4231-1-eng-GB/keybase.io-logo.png",  "https://diylogodesigns.com/blog/wp-content/uploads/2017/07/java-logo-vector-768x768.png", "https://seeklogo.com/images/E/eclipse-logo-85FE4BEA34-seeklogo.com.png", "https://www.glitchr-studio.com/wp-content/uploads/2016/07/android-studio.png", "https://www.wireshark.org/assets/theme-2015/images/sflogo.png", "https://www.fileeagle.com/data/2015/08/Process-Hacker.png", "https://1.bp.blogspot.com/-XfvM6za2bDc/WRuEaZRFmVI/AAAAAAAAAXo/hJe891_3RFARK_6XzPlU8b56hcPIfUnKQCLcB/s1600/download.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Audacity_Logo.svg/2000px-Audacity_Logo.svg.png", "https://s3.amazonaws.com/freebiesupply/large/2x/steam-logo-transparent.png", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Visual_Studio_Code_1.18_icon.svg/512px-Visual_Studio_Code_1.18_icon.svg.png", "https://www.gimp.org/images/frontpage/wilber-big.png", "https://opencv.org/assets/theme/logo.png"]

var table_location = document.getElementById('material-table-container');
 for(var x = 0; x < tools.length; x++){   
	table_location.innerHTML += `<tr>\n  <td class="mdl-data-table__cell--non-numeric ">\n    <span class="mdl-chip mdl-chip--contact">\n      <img class="mdl-chip__contact" src="${image_icons[x]}"></img>\n      <span class="mdl-chip__text">${tools[x]}</span>\n    </span>\n  </td>\n  <td class="mdl-data-table__cell--non-numeric resource-link">\n    <a href="${links[x]}">\n      ${links[x]}\n    </a>\n  </td>\n</tr>`
	}